### Variables Globales
@baseUrl = http://localhost:8080/api/v1
# Reemplaza los valores con IDs que existan en tu base de datos MySQL local
@merchantId = 1
@customerId = 1
@tokenValue = "tok_live_desktop_998877665544"


### 1. Prueba de Petición HTTP POST: Procesar Pago Exitoso
POST {{baseUrl}}/payments
Content-Type: application/json
X-Idempotency-Key: KEY-TEST-HTTP-002

{
    "merchantId": {{merchantId}},
    "customerId": {{customerId}},
    "tokenValue": {{tokenValue}},
    "amount": 33000.00,
    "currency": "ARS"
}


### 2. Prueba de Idempotencia, Doble Cobro, ejecutamos esta despues de la primera
# La idea es que devuelva el mismo código de transacción que el paso 1, sin duplicar en MySQL.
POST {{baseUrl}}/payments
Content-Type: application/json
X-Idempotency-Key: KEY-TEST-HTTP-001

{
    "merchantId": {{merchantId}},
    "customerId": {{customerId}},
    "tokenValue": {{tokenValue}},
    "amount": 25000.50,
    "currency": "ARS"
}


### 3. Prueba de Error, Comercio Inexistente (404).
POST {{baseUrl}}/payments
Content-Type: application/json

{
    "merchantId": 99999,
    "customerId": {{customerId}},
    "tokenValue": {{tokenValue}},
    "amount": 100.00,
    "currency": "ARS"
}

### 4. Prueba defensiva: JSON mal formado y monto negativo
POST {{baseUrl}}/payments
Content-Type: application/json
X-Idempotency-Key: KEY-HACK-001

{
  "merchantId": null,
  "customerId": {{customerId}},
  "tokenValue": "",
  "amount": -5000,
  "currency": "ARS"
}